server:
  port: 8080

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  cloud:
    consul:
      host: ${URL_CONSUL:localhost}
      port: ${PORT_CONSUL:8500}
      discovery:
        health-check-path: /actuator/health
        health-check-interval: 10s
        instance-id: ${spring.application.name}:${random.value}
        prefer-ip-address: true
        service-name: api-gateway

    gateway:
      server:
        webflux:
          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins: "*"
                allowedHeaders: "*"
                allowedMethods:
                  - GET
                  - POST
                  - PATCH
                  - PUT
                  - DELETE
                  - OPTIONS

          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:
            - id: identityservice
              uri: lb://ms-auth-identityservice
              predicates:
                - Path=/api/v1/auth/**,/api/v1/users/**
              filters:
                - Jwt

            - id: eventcategory
              uri: lb://ms-event-category
              predicates:
                - Path=/api/v1/events/**
              filters:
                - Jwt

            - id: enrollment
              uri: lb://ms-enrollment
              predicates:
                - Path=/api/v1/enrollments/**
              filters:
                - Jwt

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      access: unrestricted

security:
  jwt:
    secret-key: ${JWT_SECRET:F0bVQgRnuk6DRxooVWKaG0ndlgqEeI/4YXObXeOaR2Q=}